version: '3.8'

services:
  api-gateway:
    image: isdockero/onliver-api-gateway:latest
    networks:
      - service-network
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  ws-hub:
    image: isdockero/onliver-ws-hub:latest
    networks:
      - service-network
    ports:
      - target: 8080
        published: 4444
        protocol: tcp
    deploy:
      replicas: 1
      restart_policy:
        condition: any

networks:
  service-network:
    external: true