spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:3000"
              - "http://localhost"
              - "http://onliver.ru"
              - "https://onliver.ru"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: room_managment
          uri: http://room-manager:8080
          predicates:
            - Path=/room/**
          filters:
            - "RewritePath=/room/(.*), /room/$1"
            - "RewritePath=/room, /room"

        - id: token_managment
          uri: http://room-manager:8080
          predicates:
            - Path=/token
          filters:
            - "RewritePath=/token(.*), /token$1"

        - id: token_managment2
          uri: http://room-manager:8080
          predicates:
            - Path=/token/**
          filters:
            - "RewritePath=/token(.*), /token$1"

        - id: livekit_ws_redirect
          uri: ws://onliver.ru:7880
          predicates:
            - Path=/livekit/**
            - Header=Upgrade, websocket
          filters:
            - "RewritePath=/livekit/(.*), /$1"
            
        - id: livekit_http_redirect
          uri: http://onliver.ru:7880
          predicates:
            - Path=/livekit/**
          filters:
            - "RewritePath=/livekit/(.*), /$1"
        
        - id: livekit_ws_redirect2
          uri: ws://onliver.ru:7880
          predicates:
            - Path=/livekit
            - Header=Upgrade, websocket
          filters:
            - "RewritePath=/livekit(.*), /$1"
            
        - id: livekit_http_redirect2
          uri: http://onliver.ru:7880
          predicates:
            - Path=/livekit
          filters:
            - "RewritePath=/livekit(.*), /$1"

        - id: livekit_wh
          uri: http://room-manager:8080
          predicates:
            - Path=/api/livekit/webhook/**
          filters:
            - 'RewritePath=/api/livekit/webhook/(?<remaining>.*), /${remaining}'

        - id: livekit_wh_2
          uri: http://room-manager:8080
          predicates:
            - Path=/api/livekit/webhook
          filters:
            - 'RewritePath=/api/livekit/webhook(.*), /$1'

        - id: translation_manager
          uri: http://translation-manager:8080
          predicates:
            - Path=/translation/**
          filters:
            - "RewritePath=/translation/(.*), /translation/$1"

        - id: content_manager
          uri: http://content-manager:8080
          predicates:
            - Path=/content/**
          filters:
            - "RewritePath=/content/(.*), /content/$1"

        - id: content_manager1
          uri: http://content-manager:8080
          predicates:
            - Path=/content
          filters:
            - "RewritePath=/content(.*), /content$1"



server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: admin123
    key-password: admin123
    key-store-type: JKS
    key-alias: onliverssl